#数据库配置变量
HOSTNAME = '127.0.0.1'
PORT = '3306'
DATABASE = 'example'
USERNAME = 'root'
PASSWORD = '123456'
DB_URI = 'mysql+pymysql://{}:{}@{}:{}/{}?charset=utf8'.format(USERNAME, PASSWORD, HOSTNAME, PORT, DATABASE)

SQLALCHEMY_DATABASE_URI = DB_URI
SQLALCHEMY_TRACK_MODIFICATIONS = True

SECRET_KEY = "vnhiprehbnviuor"


# 邮箱配置
# QQ邮箱为例
MAIL_SERVER = 'smtp.163.com'
MAIL_PORT = 465
MAIL_USE_TLS = False
MAIL_USE_SSL = True
MAIL_DEBUG = True
MAIL_USERNAME = "xwd19991229@163.com"
MAIL_PASSWORD = "FZECHLQBGHMABNQT"
MAIL_DEFAULT_SENDER = "xwd19991229@163.com"
# SECURITY_EMAIL_SENDER = 'valid_email@163.com'
# MAIL_MAX_EMAILS =
# MAIL_SUPPRESS_SEND  =
# MAIL_ASCII_ATTACHMENTS =